name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    strategy:
      matrix:
        os: ${{ github.actor == 'dependabot[bot]' && fromJson('["ubuntu-latest"]') || fromJson('["ubuntu-latest", "macos-latest", "windows-latest"]') }}
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          post-run: |
            echo "test" | tee "${{ runner.temp }}/test.txt"
            if [ -f "${{ runner.temp }}/post.sh" ]; then
              "${{ runner.temp }}/post.sh"
            fi

      - name: Test Local Action (login shell)
        id: test-longin-shell
        uses: ./
        with:
          shell: bash -l -ex {0}
          post-run: |
            echo "test" | tee "${{ runner.temp }}/test.txt"
            if [ -f "${{ runner.temp }}/post.sh" ]; then
              "${{ runner.temp }}/post.sh"
            fi

      - name: Test Local Action (Python)
        id: test-python
        uses: ./
        with:
          shell: python
          post-run: |
            print("Hello, world!")

      - name: Test Local Action (pwsh)
        id: test-pwsh
        uses: ./
        with:
          shell: pwsh
          post-run: |
            Write-Host "Hello World!!"

      - name: Test Local Action (powershell)
        id: test-powershell
        uses: ./
        with:
          shell: powershell
          post-run: |
            Write-Host "Hello World!!"
        if: runner.os == 'Windows'

      - name: Test Local Action (cmd)
        id: test-cmd
        uses: ./
        with:
          shell: cmd
          post-run: |
            echo "Hello World!!"
        if: runner.os == 'Windows'

      - name: Test Local Action (Dotnet)
        id: test-dotnet
        uses: ./
        with:
          shell: dotnet
          post-run: |
            Console.WriteLine("Hello, world!");

      - name: Test file
        run: |
          test ! -f "${{ runner.temp }}/test.txt"
